name: Chess ➜ TickTick (Daily)

on:
  schedule:
    - cron:  '*/30 * * * *'   # atualiza a cada 30 min
  workflow_dispatch:

jobs:
  chess:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }

      - name: Install dependencies
        run: npm install

      - name: Run chess daily bot
        env:
          CHESS_USER: ${{ secrets.CHESS_USER }}
          TICKTICK_ACCESS_TOKEN: ${{ secrets.TICKTICK_ACCESS_TOKEN }}
          TICKTICK_PROJECT_ID: ${{ secrets.TICKTICK_PROJECT_ID }}
          USER_EMAIL:     ${{ secrets.USER_EMAIL }}
          DAILY_LIMIT:   ${{ secrets.DAILY_LIMIT || 10 }}
          TIMEZONE:      ${{ secrets.TIMEZONE || 'UTC' }}
          NODE_ENV: production
        run: node scripts/chess-daily-bot.js
